// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/shharn/golang-clean-architecture/model"

// TodoUsecase is an autogenerated mock type for the TodoUsecase type
type TodoUsecase struct {
	mock.Mock
}

// GetAllTodos provides a mock function with given fields:
func (_m *TodoUsecase) GetAllTodos() []model.Todo {
	ret := _m.Called()

	var r0 []model.Todo
	if rf, ok := ret.Get(0).(func() []model.Todo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Todo)
		}
	}

	return r0
}
